site_name: Codename H.E.A.L.
site_url: https://chebura.github.io/fiction
repo_url: https://github.com/chebura/fiction
edit_uri: edit/main/my-project/docs/
view_uri: view/main/my-project/docs/

nav:
    - 'О проекте': 'index.md'
    - 'Авторские права': 'copyright.md'
    - 'heal/TIM_BRC_001.md'
    - 'heal/TIM_BRC_002.md'
    - 'heal/TIM_BRC_003.md'
    - 'heal/TIM_BRC_004.md'
    - 'heal/TIM_BRC_005.md'
    - 'heal/TIM_BRC_100.md'

use_directory_urls: false

theme:
  name: material
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    #- toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: blue gray
      accent: blue gray
      toggle:
        icon: material/brightness-7
        name: Перейти на тёмную сторону
    - scheme: slate
      primary: blue gray
      accent: blue gray
      toggle:
        icon: material/brightness-4
        name: Перейти на светлую сторону
  language: ru
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    repo: fontawesome/brands/git-alt
    view: material/eye

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: 
        - en
        - ru
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      locale: ru
      enabled: true


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
