site_name: HEAL
# site_url: http://mrald.narod.ru
nav:
    - 'index.md'
    - 'about/about.md'
    - 'merged.md'
use_directory_urls: false
theme:
    name: readthedocs
    nav_style: dark
    locale: ru