site_name: HEAL
site_url: https://chebura.github.io/fiction
nav:
    - 'index.md'
    - 'copyright.md'
    - 'heal/001_000_TIM_BRC.md'
use_directory_urls: false

theme:
  name: readthedocs
  nav_style: dark
  
  # Necessary for search to work properly
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: ru
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      lang: 
        - en
        - ru