site_name: HEAL
# site_url: http://mrald.narod.ru
nav:
    - 'index.md'
    - 'copyright.md'
    - 'heal/001_000_TIM_BRC.md'
use_directory_urls: false
theme:
    name: readthedocs
    nav_style: dark
    locale: ru
