site_name: HEALhttps://github.com/Chebura/fiction/blob/main/my-project/mkdocs.yml
# site_url: http://mrald.narod.ru
nav:
    - 'index.md'
    - 'copyright.md'
    - 'heal/001.000.TIM.BRC.md'
use_directory_urls: false
repo_url: https://github.com/Chebura/Chebura.github.io
theme:
    name: readthedocs
    nav_style: dark
    locale: ru
